apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-microservice
  labels:
    app: basic-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basic-microservice
  template:
    metadata:
      labels:
        app: basic-microservice
    spec:
      containers:
        - name: basic-microservice
          image: dinhcam89/basic-js-app:v0.0.1
          ports:
            - containerPort: 3000
          env:
            - name: MESSAGE
              value: "Hello from Kubernetes!"

---
apiVersion: v1
kind: Service
metadata:
  name: basic-microservice-service
spec:
  selector:
    app: basic-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
